# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

central_loss: 1
qmix_loss: 1
w: 0.1 # $\alpha$ in the paper
hysteretic_qmix: True # False -> CW-QMIX, True -> OW-QMIX

central_mixing_embed_dim: 256
central_action_embed: 1
central_mac: "basic_central_mac_teach"
central_agent: "central_rnn"
central_rnn_hidden_dim: 64
central_mixer: "ff"

name: "ow_qmix_teach5"

agent_all: "rnn_all" # Default rnn agent
mac: "basic_mac_teach" # Basic controller
learner: "max_q_learner_teach"
target_update_interval_forteach: 1
lr_time: 1.0
#agent: "rnn" # Default rnn agent
